# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Auth Build

on:
  push:
    branches: '*'
    paths:
      - 'auth/src/**'
      - 'auth/tests/**'

  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'auth/src/**'
      - 'auth/tests/**'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./auth

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make ci-prebuild
          make build
      - name: Test with pytest
        run: |
          make cover
      - name: Build Image
        run: |
          docker build . --file Dockerfile --tag auth:dev